<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AwesomeAssertions.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="FakeItEasy" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\pipeline\Formats\RepoQL.Formats.Python\RepoQL.Formats.Python.csproj" />
    <ProjectReference Include="..\RepoQL.Testing\RepoQL.Testing.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Fixtures\**\*.py" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Fixtures\**\*.pyi" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
