<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DuckDB.NET.Data.Full" Version="1.4.1"/>
    <PackageReference Include="Ignore" Version="0.2.1"/>
    <PackageReference Include="System.IO.Hashing" Version="9.0.3"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RepoQL.Contracts\RepoQL.Contracts.csproj" />
    <ProjectReference Include="..\RepoQL.Data.DuckDB\RepoQL.Data.DuckDB.csproj" />
    <ProjectReference Include="..\RepoQL.FileSystem\RepoQL.FileSystem.csproj" />
    <ProjectReference Include="..\Indexing\RepoQL.Indexing\RepoQL.Indexing.csproj" />
    <ProjectReference Include="..\Formats\RepoQL.Formats.Markdown\RepoQL.Formats.Markdown.csproj" />
    <ProjectReference Include="..\Formats\RepoQL.Formats.Mermaid\RepoQL.Formats.Mermaid.csproj" />
    <ProjectReference Include="..\Formats\RepoQL.Formats.DotNet\RepoQL.Formats.DotNet.csproj" />
    <ProjectReference Include="..\Formats\RepoQL.Formats.GraphQL\RepoQL.Formats.GraphQL.csproj" />
    <ProjectReference Include="..\Formats\RepoQL.Formats.TypeScript\RepoQL.Formats.TypeScript.csproj" />
    <ProjectReference Include="..\Formats\RepoQL.Formats.PHP\RepoQL.Formats.PHP.csproj" />
    <ProjectReference Include="..\Formats\RepoQL.Formats.Terraform\RepoQL.Formats.Terraform.csproj" />
    <ProjectReference Include="..\Formats\RepoQL.Formats.Sql\RepoQL.Formats.Sql.csproj" />
    <ProjectReference Include="..\Formats\RepoQL.Formats.CSS\RepoQL.Formats.CSS.csproj" />
    <ProjectReference Include="..\RepoQL.Templating\RepoQL.Templating.csproj" />
    <ProjectReference Include="..\RepoQL.Embeddings\RepoQL.Embeddings.csproj" />
    <ProjectReference Include="..\RepoQL.Documentation\RepoQL.Documentation.csproj" />
    <ProjectReference Include="..\RepoQL.Mcp.Client\RepoQL.Mcp.Client.csproj" />
    <ProjectReference Include="..\RepoQL.LLM.Client\RepoQL.LLM.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.Tokenizers" Version="0.22.0" />
  </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="RepoQL.Tests"/>
    </ItemGroup>

</Project>
