<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>false</IsTestProject>
    <UseTestingPlatform>false</UseTestingPlatform>
    <TestingPlatformDotnetTestSupport>false</TestingPlatformDotnetTestSupport>
    <IsTestingPlatformApplication>false</IsTestingPlatformApplication>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Framework" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="FakeItEasy" />
    <PackageReference Include="AwesomeAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\contracts\RepoQL.Contracts\RepoQL.Contracts.csproj" />
    <ProjectReference Include="..\..\app\RepoQL.Core\RepoQL.Core.csproj" />
    <ProjectReference Include="..\..\data\RepoQL.Data.DuckDB\RepoQL.Data.DuckDB.csproj" />
    <ProjectReference Include="..\..\pipeline\RepoQL.Indexing\RepoQL.Indexing.csproj" />
    <ProjectReference Include="..\..\infra\RepoQL.FileSystem\RepoQL.FileSystem.csproj" />
  </ItemGroup>

</Project>
