<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="**/*.md" />
        <EmbeddedResource Include="**/*.csv" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\RepoQL.FileSystem\RepoQL.FileSystem.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <Folder Include="repoql\tools\import\" />
      <Folder Include="repoql\tools\query\views\" />
    </ItemGroup>
    
</Project>
