<Project Sdk="Aspire.AppHost.Sdk/13.1.0">
    
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>262cdc7c-4509-4bad-ade1-3d4cc013a93e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RepoQL.ConsoleApp\RepoQL.ConsoleApp.csproj" />
    <ProjectReference Include="..\RepoQL.Contracts\RepoQL.Contracts.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\RepoQL.Protocol\RepoQL.Protocol.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\RepoQL.Web\RepoQL.Web.csproj" />
  </ItemGroup>

</Project>
