<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AwesomeAssertions.Analyzers" Version="9.0.8">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.0.1" />
        <PackageReference Include="TUnit" Version="0.75.30" />
        <PackageReference Include="AwesomeAssertions" Version="9.2.1" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\RepoQL.Contracts\RepoQL.Contracts.csproj" />
    </ItemGroup>

</Project>