<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>repoql-embedding</AssemblyName>

    <!-- dotnet publish produces a container image by default -->
    <PublishProfile>DefaultContainer</PublishProfile>
    <ContainerRepository>repoql-embedding</ContainerRepository>
    <ContainerFamily>noble</ContainerFamily>
    <PublishTrimmed>false</PublishTrimmed>
    <UserSecretsId>dbcf7209-9611-44dd-924e-b35e955f586a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ContainerPort Include="8080" Type="tcp" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="DuckDB.NET.Data.Full" />
    <PackageReference Include="OpenTelemetry" />
    <PackageReference Include="Google.Cloud.Firestore" />
    <PackageReference Include="Google.Cloud.Storage.V1" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RepoQL.Cloud.Auth\RepoQL.Cloud.Auth.csproj" />
    <ProjectReference Include="..\RepoQL.Embedding.Proto\RepoQL.Embedding.Proto.csproj" />
    <ProjectReference Include="..\RepoQL.Embedding.Storage\RepoQL.Embedding.Storage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RepoQL.Embedding.Service.Tests" />
  </ItemGroup>

</Project>
