<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

  <ItemGroup>
      <EmbeddedResource Include="ILLink.Descriptors.xml">
          <LogicalName>ILLink.Descriptors.xml</LogicalName>
      </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
      <PackageReference Include="LLMSharp.Anthropic.Tokenizer" />
      <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
      <PackageReference Include="System.Diagnostics.DiagnosticSource" />
      <PackageReference Include="System.IO.Hashing" />
  </ItemGroup>


</Project>
