<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <UseTestingPlatform>true</UseTestingPlatform>
    </PropertyGroup>

  <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" />
      <PackageReference Include="AwesomeAssertions.Analyzers">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
      <PackageReference Include="TUnit" />
      <PackageReference Include="AwesomeAssertions" />
      <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
      <PackageReference Include="Serilog" />
        <PackageReference Include="Grpc.AspNetCore" />
        <PackageReference Include="Microsoft.AspNetCore.TestHost" />
</ItemGroup>

  <ItemGroup>
        <ProjectReference Include="..\RepoQL.Testing\RepoQL.Testing.csproj" />
        <ProjectReference Include="..\..\RepoQL.Data.DuckDB\RepoQL.Data.DuckDB.csproj" />
        <ProjectReference Include="..\..\Formats\RepoQL.Formats.Markdown\RepoQL.Formats.Markdown.csproj" />
        <ProjectReference Include="..\..\Formats\RepoQL.Formats.Mermaid\RepoQL.Formats.Mermaid.csproj" />
        <ProjectReference Include="..\..\Formats\RepoQL.Formats.DotNet\RepoQL.Formats.DotNet.csproj" />
        <ProjectReference Include="..\..\RepoQL.Core\RepoQL.Core.csproj" />
        <ProjectReference Include="..\..\RepoQL.Contracts\RepoQL.Contracts.csproj" />
        <ProjectReference Include="..\..\RepoQL.Documentation\RepoQL.Documentation.csproj" />
        <ProjectReference Include="..\..\RepoQL.ConsoleApp\RepoQL.ConsoleApp.csproj" />
</ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Doc1.md" />
    <EmbeddedResource Include="Resources\Doc2.md" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="CSourceRepoQLtest-results.txt" />
  </ItemGroup>

</Project>
