<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <UseTestingPlatform>true</UseTestingPlatform>
    </PropertyGroup>

  <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.1" />
      <PackageReference Include="AwesomeAssertions.Analyzers" Version="9.0.8">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.0.1" />
      <PackageReference Include="TUnit" Version="0.75.30" />
      <PackageReference Include="AwesomeAssertions" Version="9.2.1" />
      <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.1.0" />
        <PackageReference Include="Grpc.AspNetCore" Version="2.62.0" />
        <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="9.0.0" />
</ItemGroup>

  <ItemGroup>
        <ProjectReference Include="..\RepoQL.Testing\RepoQL.Testing.csproj" />
        <ProjectReference Include="..\..\RepoQL.Data.DuckDB\RepoQL.Data.DuckDB.csproj" />
        <ProjectReference Include="..\..\Formats\RepoQL.Formats.Markdown\RepoQL.Formats.Markdown.csproj" />
        <ProjectReference Include="..\..\Formats\RepoQL.Formats.Mermaid\RepoQL.Formats.Mermaid.csproj" />
        <ProjectReference Include="..\..\Formats\RepoQL.Formats.DotNet\RepoQL.Formats.DotNet.csproj" />
        <ProjectReference Include="..\..\RepoQL.Core\RepoQL.Core.csproj" />
        <ProjectReference Include="..\..\RepoQL.Contracts\RepoQL.Contracts.csproj" />
        <ProjectReference Include="..\..\RepoQL.Documentation\RepoQL.Documentation.csproj" />
        <ProjectReference Include="..\..\RepoQL.ConsoleApp\RepoQL.ConsoleApp.csproj" />
</ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Doc1.md" />
    <EmbeddedResource Include="Resources\Doc2.md" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="CSourceRepoQLtest-results.txt" />
  </ItemGroup>

</Project>
