<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\RepoQL.Contracts\RepoQL.Contracts.csproj" />
      <ProjectReference Include="..\..\RepoQL.FileSystem\RepoQL.FileSystem.csproj" />
      <ProjectReference Include="..\..\RepoQL.Data.DuckDB\RepoQL.Data.DuckDB.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="DotNext.Threading" Version="5.26.0" />
      <PackageReference Include="DuckDB.NET.Data.Full" Version="1.4.1" />
      <PackageReference Include="LibGit2Sharp" Version="0.30.0" />
    </ItemGroup>

</Project>
