<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <InvariantCulture>true</InvariantCulture>
    </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates/**/*.liquid" />
  </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\RepoQL.Templating\RepoQL.Templating.csproj" />
      <ProjectReference Include="..\..\RepoQL.Contracts\RepoQL.Contracts.csproj" />
    </ItemGroup>

</Project>
